# Generated by Django 4.0.3 on 2022-05-28 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_event_machine_mach_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 28, 10, 48, 38, 478532)),
        ),
    ]
